import React from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, List, ListItem, ListItemText, Skeleton, Typography } from '@mui/material';
import api from '../api/axios';
import { surveyId } from './surveyLifecycle';

const newKey=()=>globalThis.crypto?.randomUUID?.() || 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
const fallbackKeys=new Map();const attemptsBySurvey=new Map();const completedBySurvey=new Map();const storageKey=id=>`reminder-launch-key:${id}`;
const keyFor=id=>{try{const stored=globalThis.sessionStorage?.getItem(storageKey(id));if(stored)return stored;const key=newKey();globalThis.sessionStorage?.setItem(storageKey(id),key);return key;}catch{if(!fallbackKeys.has(id))fallbackKeys.set(id,newKey());return fallbackKeys.get(id);}};
const rotateKey=id=>{fallbackKeys.delete(id);try{globalThis.sessionStorage?.removeItem(storageKey(id));}catch{}};
const ReminderCampaignDialog=({open,survey,onClose,onAccepted,unsavedChanges={},pendingOperations={}})=>{
  const [readiness,setReadiness]=React.useState(null);const [readinessSurveyId,setReadinessSurveyId]=React.useState(null);const [error,setError]=React.useState('');const [loading,setLoading]=React.useState(false);const [submitting,setSubmitting]=React.useState(false);const request=React.useRef(0);const id=surveyId(survey);const idRef=React.useRef(id);const acceptedRef=React.useRef(onAccepted);const mounted=React.useRef(false);idRef.current=id;acceptedRef.current=onAccepted;
  React.useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  React.useEffect(()=>{const version=++request.current;const active=id&&attemptsBySurvey.get(id);const completed=id&&completedBySurvey.get(id);setSubmitting(Boolean(active));if(completed){completedBySurvey.delete(id);setLoading(false);setReadiness(null);setReadinessSurveyId(null);acceptedRef.current?.(completed);return undefined;}if(active)active.done.then(()=>{if(!mounted.current||version!==request.current||id!==idRef.current)return;request.current+=1;setSubmitting(false);setLoading(false);if(active.result?.ok){setReadiness(null);setReadinessSurveyId(null);if(!active.acceptedNotified){active.acceptedNotified=true;completedBySurvey.delete(id);acceptedRef.current?.(active.result.data);}}});if(!open||!id)return undefined;keyFor(id);const controller=new AbortController();setLoading(true);setError('');setReadiness(null);setReadinessSurveyId(null);api.get(`/surveys/${id}/reminder-readiness`,{signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted&&version===request.current){setReadiness(data);setReadinessSurveyId(id);}}).catch(err=>{if(!controller.signal.aborted&&version===request.current)setError(err.response?.data?.message||'Unable to preview reminder campaign.');}).finally(()=>{if(!controller.signal.aborted&&version===request.current)setLoading(false);});return()=>controller.abort();},[open,id]);
  const dirty=Object.values(unsavedChanges).some(Boolean);const pending=Object.values(pendingOperations).some(Boolean);const blockers=readiness?.blockers||[];const canLaunch=readinessSurveyId===id&&readiness?.canLaunch&&readiness.targetCount>0&&blockers.length===0&&!dirty&&!pending&&!submitting;
  const submit=async()=>{if(!canLaunch||attemptsBySurvey.has(id))return;const targetId=id;let finish;const attempt={done:new Promise(resolve=>{finish=resolve;})};const key=keyFor(targetId);attemptsBySurvey.set(targetId,attempt);setSubmitting(true);setError('');try{const {data}=await api.post(`/surveys/${targetId}/launches`,{kind:'reminder'},{headers:{'Idempotency-Key':key}});attempt.result={ok:true,data};rotateKey(targetId);if(mounted.current&&targetId===idRef.current&&!attempt.acceptedNotified){request.current+=1;setReadiness(null);setReadinessSurveyId(null);attempt.acceptedNotified=true;acceptedRef.current?.(data);}else if(!attempt.acceptedNotified)completedBySurvey.set(targetId,data);}catch(err){attempt.result={ok:false,error:err};if(!mounted.current||targetId!==idRef.current)return;if(err.response?.status===422&&err.response?.data?.details){setReadiness({...err.response.data.details,canLaunch:false});setReadinessSurveyId(targetId);}else if(err.response?.status===409){setReadiness(null);setReadinessSurveyId(null);}setError(err.response?.data?.message||'Unable to queue reminder campaign.');}finally{if(attemptsBySurvey.get(targetId)===attempt)attemptsBySurvey.delete(targetId);finish();if(mounted.current&&targetId===idRef.current)setSubmitting(false);}};
  return <Dialog open={open} onClose={()=>!submitting&&onClose?.()} fullWidth maxWidth="sm" aria-describedby="reminder-consequences" aria-busy={loading||submitting}>
    <DialogTitle>Send bulk reminder</DialogTitle><DialogContent>
      <DialogContentText id="reminder-consequences">This creates one auditable reminder campaign using the saved localized reminder templates. It does not resend invitations or change responses. Eligibility is checked again immediately before each provider request.</DialogContentText>
      {loading&&<Skeleton variant="rectangular" height={90} sx={{mt:2}} />}
      {readiness&&<Typography sx={{mt:2}} component="p" variant="h6">{readiness.targetCount} incomplete eligible {readiness.targetCount===1?'respondent':'respondents'} will be targeted</Typography>}
      {readiness?.templateCoverage?.length>0&&<List dense aria-label="Reminder template coverage">{readiness.templateCoverage.map(item=><ListItem key={item.language}><ListItemText primary={`${item.language}: ${item.covered?'ready':'missing'}`} /></ListItem>)}</List>}
      {(dirty||pending)&&<Alert severity="warning" sx={{mt:2}}>{pending?'Wait for current survey updates to finish.':'Save or revert unsaved survey changes before sending reminders.'}</Alert>}
      {blockers.map((item,index)=><Alert severity="error" sx={{mt:1}} key={`${item.code}-${index}`}>{item.message}</Alert>)}
      {readiness?.warnings?.map((item,index)=><Alert severity="warning" sx={{mt:1}} key={`${item.code}-${index}`}>{item.message}</Alert>)}
      {error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}
    </DialogContent><DialogActions><Button onClick={onClose} disabled={submitting}>Cancel</Button><Button variant="contained" onClick={submit} disabled={!canLaunch}>{submitting?'Queueing…':'Send reminders'}</Button></DialogActions>
  </Dialog>;
};
export default ReminderCampaignDialog;
