#!/bin/bash
# Liquibase command script generated by Terraform

liquibase \
  --url="jdbc:postgresql://terraform-20241204194744041200000001.cb4kmcse0a7d.us-east-1.rds.amazonaws.com:5432/ONA" \
  --username="DbAdmin" \
  --password="password!" \
  --changeLogFile="changelogs/master-changelog.xml" \
  --logLevel=info \
  "$@"