'use strict';

const os = require('os');
const crypto = require('crypto');
const fs = require('fs');
const dotenvFlow = require('dotenv-flow');
const { Pool } = require('pg');
const { ResendProvider, buildInvitationPayload, payloadHash, classifyProviderError, sanitizeProviderMessage, reserveProviderRateWithAvailabilityInTransaction, unlockAdvisoryLocksAndRelease } = require('./email');
const { environmentName } = require('./lifecycle');

dotenvFlow.config();

function createPool(env=process.env){return new Pool({user:env.DB_USER,password:env.DB_PASSWORD,host:env.DB_HOST,port:env.DB_PORT,database:env.DB_NAME||'ONA',ssl:env.DB_SSL==='true'?{ca:env.DB_SSL_CA?fs.readFileSync(env.DB_SSL_CA,'utf8'):undefined,rejectUnauthorized:Boolean(env.DB_SSL_CA)}:undefined});}
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const isOutsideProviderIdempotencyWindow=(startedAt,now,hours)=>Boolean(startedAt)&&new Date(startedAt).getTime()<=new Date(now).getTime()-hours*3600000;
const canRetryAmbiguous=({firstProviderStartedAt,providerAttemptCount,createdAt,now,idempotencyHours,maxAttempts,maxAgeHours})=>Boolean(firstProviderStartedAt)&&!isOutsideProviderIdempotencyWindow(firstProviderStartedAt,now,idempotencyHours)&&Number(providerAttemptCount)<maxAttempts&&new Date(createdAt).getTime()>new Date(now).getTime()-maxAgeHours*3600000;
const bounded=(value,max=500)=>value===null||value===undefined?null:sanitizeProviderMessage(value).slice(0,max);
const buildDeliveryPayload=(row,surveyName,environment)=>{
  const renderInputs=typeof row.render_inputs==='string'?JSON.parse(row.render_inputs):row.render_inputs;
  return buildInvitationPayload({to:row.to_address,sender:row.sender,subject:row.subject,bodyText:row.body_text,surveyBaseUrl:row.survey_base_url,surveyName:renderInputs?.surveyName||surveyName,token:row.uuid,language:row.language,deliveryId:row.id,environment,rendererVersion:row.renderer_version});
};

class DeliveryWorker {
  constructor({pool,provider,env=process.env,clock=()=>new Date(),random=Math.random,sleepFn=sleep,instanceId}={}){
    this.pool=pool;this.env=env;this.environment=environmentName(env);this.rateBudgetEnvironment=env.EMAIL_RATE_BUDGET_ENV||this.environment;this.provider=provider;this.clock=clock;this.random=random;this.sleep=sleepFn;
    this.instanceId=instanceId||`${env.DEPLOYMENT_ID||'local'}/${os.hostname()}/${process.pid}/${crypto.randomUUID()}`;this.release=env.RELEASE_REVISION||env.REVISION||'local';
    this.leaseSeconds=Math.max(20,Number(env.EMAIL_LEASE_SECONDS||60));this.maxAttempts=Math.max(1,Number(env.EMAIL_MAX_ATTEMPTS||6));this.maxAgeHours=Math.max(1,Number(env.EMAIL_MAX_AGE_HOURS||72));this.idempotencyHours=Math.min(23,Math.max(1,Number(env.EMAIL_PROVIDER_IDEMPOTENCY_HOURS||23)));this.rate=Math.max(1,Number(env.EMAIL_RATE_PER_SECOND||5));this.providerAccountScope=String(env.RESEND_PROVIDER_ACCOUNT_SCOPE||'').trim();this.reminderCapable=Boolean(this.providerAccountScope&&this.providerAccountScope.length<=128);this.stopped=false;this.claiming=false;this.lastError=null;
  }
  async heartbeat(){await this.pool.query(`INSERT INTO email_worker_heartbeats(environment,worker_instance,release_revision,enabled,claiming,reminder_capable,provider_account_scope,heartbeat_at,last_error,started_at) VALUES($1,$2,$3,true,$4,$5,$6,now(),$7,now()) ON CONFLICT(environment,worker_instance) DO UPDATE SET release_revision=excluded.release_revision,enabled=true,claiming=excluded.claiming,reminder_capable=excluded.reminder_capable,provider_account_scope=excluded.provider_account_scope,heartbeat_at=now(),last_error=excluded.last_error`,[this.environment,this.instanceId,this.release,this.claiming,this.reminderCapable,this.reminderCapable?this.providerAccountScope:null,this.lastError?bounded(this.lastError):null]);}
  async control(){const result=await this.pool.query('SELECT claiming_enabled,minimum_release FROM email_worker_control WHERE environment=$1',[this.environment]);const row=result.rows[0];return Boolean(row?.claiming_enabled&&(!row.minimum_release||this.release===row.minimum_release));}
  async claim(){const client=await this.pool.connect();try{await client.query('BEGIN');const control=await client.query('SELECT claiming_enabled,minimum_release FROM email_worker_control WHERE environment=$1 FOR SHARE',[this.environment]);if(!control.rows[0]?.claiming_enabled||control.rows[0].minimum_release&&this.release!==control.rows[0].minimum_release){await client.query('COMMIT');return null;}
      const selected=await client.query(`SELECT d.id,d.status,d.attempt_count,d.created_at,d.lease_token,l.kind AS launch_kind FROM survey_email_deliveries d JOIN survey_launches l ON l.id=d.launch_id WHERE ($1::boolean OR l.kind<>'reminder') AND (l.kind<>'reminder' OR l.provider_account_scope=$2) AND (((d.status IN ('pending','retry_wait') OR ($1::boolean AND d.status IN ('reminder_pending','reminder_retry_wait'))) AND d.next_attempt_at<=now()) OR (d.status='leased' AND d.lease_expires_at<=now()) OR ($1::boolean AND d.status='reminder_leased' AND d.lease_expires_at<=now())) ORDER BY d.next_attempt_at,d.created_at FOR UPDATE OF d SKIP LOCKED LIMIT 1`,[this.reminderCapable,this.providerAccountScope]);
      if(!selected.rows[0]){await client.query('COMMIT');return null;}const previous=selected.rows[0];
      if(previous.status==='leased'||previous.status==='reminder_leased'){
        const boundary=await client.query(`SELECT MIN(provider_started_at) FILTER (WHERE outcome='uncertain' OR (lease_token=$2 AND outcome='in_progress')) AS first_ambiguous_provider_started_at,COUNT(provider_started_at)::int AS provider_attempt_count,COALESCE(bool_or(lease_token=$2 AND outcome='in_progress' AND provider_started_at IS NOT NULL),false) AS current_provider_started FROM survey_email_attempts WHERE delivery_id=$1`,[previous.id,previous.lease_token]);
        const crossed=boundary.rows[0]?.current_provider_started===true;
        const outsideWindow=isOutsideProviderIdempotencyWindow(boundary.rows[0]?.first_ambiguous_provider_started_at,this.clock(),this.idempotencyHours);
        const exhausted=!canRetryAmbiguous({firstProviderStartedAt:boundary.rows[0]?.first_ambiguous_provider_started_at,providerAttemptCount:boundary.rows[0]?.provider_attempt_count,createdAt:previous.created_at,now:this.clock(),idempotencyHours:this.idempotencyHours,maxAttempts:this.maxAttempts,maxAgeHours:this.maxAgeHours});
        await client.query(`UPDATE survey_email_attempts SET finished_at=COALESCE(finished_at,now()),outcome=CASE WHEN outcome='in_progress' THEN $2 ELSE outcome END,error_message=CASE WHEN outcome='in_progress' THEN $3 ELSE error_message END WHERE delivery_id=$1 AND outcome='in_progress'`,[previous.id,crossed?'uncertain':'cancelled',crossed?'lease expired after provider boundary':'lease expired before provider boundary']);
        if(crossed&&(outsideWindow||exhausted)){
          await client.query(`UPDATE survey_email_deliveries SET status='uncertain',dispatch_failed_at=now(),lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=now(),last_error_code=$2,last_error_message='Provider acceptance could not be reconciled safely' WHERE id=$1`,[previous.id,outsideWindow?'idempotency_window_expired':'ambiguous_attempts_exhausted']);
          await client.query('COMMIT');return null;
        }
      }
      const token=crypto.randomUUID();const leaseStatus=previous.launch_kind==='reminder'?'reminder_leased':'leased';const updated=await client.query(`UPDATE survey_email_deliveries SET status=$5,lease_owner=$2,lease_token=$3,lease_expires_at=now()+($4::text||' seconds')::interval,attempt_count=attempt_count+1,updated_at=now() WHERE id=$1 RETURNING *`,[previous.id,this.instanceId,token,this.leaseSeconds,leaseStatus]);const delivery={...updated.rows[0],launch_kind:previous.launch_kind};
      await client.query(`INSERT INTO survey_email_attempts(delivery_id,attempt_number,lease_token,outcome) VALUES($1,$2,$3,'in_progress')`,[delivery.id,delivery.attempt_count,token]);await client.query('COMMIT');return delivery;
    }catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}
  async startProviderRequest(delivery){const client=await this.pool.connect();let globalBoundaryLock=false;let surveyBoundaryLock=false;let addressBoundaryLock=false;let addressBoundaryKey=null;try{await client.query('BEGIN');
      await client.query(`SELECT pg_advisory_lock(hashtextextended($1,0))`,[`email-provider-boundary:${this.environment}`]);globalBoundaryLock=true;
      const control=(await client.query(`SELECT claiming_enabled,minimum_release FROM email_worker_control WHERE environment=$1 FOR SHARE`,[this.environment])).rows[0];
      const sendingControl=(await client.query(`SELECT sending_enabled,minimum_release FROM email_sending_control WHERE environment=$1 FOR SHARE`,[this.environment])).rows[0];
      await client.query(`SELECT pg_advisory_lock(hashtextextended($1,0))`,[`survey-provider-boundary:${delivery.survey_id}`]);surveyBoundaryLock=true;
      const survey=(await client.query(`SELECT id,name,lifecycle_status,archived_at FROM survey WHERE id=$1 FOR SHARE`,[delivery.survey_id])).rows[0];
      const result=await client.query(`SELECT d.*,r.uuid,r.can_respond,r.response,t.body_text,l.cancelled_at,l.kind AS launch_kind,l.provider_account_scope AS launch_provider_account_scope FROM survey_email_deliveries d JOIN respondent r ON r.respondent_id=d.respondent_id AND r.survey_id=d.survey_id JOIN survey_launches l ON l.id=d.launch_id JOIN survey_launch_templates t ON t.launch_id=d.launch_id AND t.language=d.language WHERE d.id=$1 AND d.status IN ('leased','reminder_leased') AND d.lease_token=$2 FOR UPDATE OF d FOR SHARE OF r`,[delivery.id,delivery.lease_token]);
      const row=result.rows[0];if(!row||!survey){await client.query('COMMIT');return {action:'stale'};}
      row.survey_name=survey.name;
      if(row.cancellation_requested_at||row.cancelled_at||survey.lifecycle_status!=='active'||survey.archived_at){await this.cancel(client,row,'survey_inactive');await client.query('COMMIT');return {action:'cancelled'};}
      if(row.launch_kind==='reminder'&&row.launch_provider_account_scope!==this.providerAccountScope){await this.releaseWithoutSend(client,row,'provider_scope_mismatch');await client.query('COMMIT');return {action:'disabled'};}
      if(!control?.claiming_enabled||(control.minimum_release&&this.release!==control.minimum_release)||!sendingControl?.sending_enabled||(sendingControl.minimum_release&&this.release!==sendingControl.minimum_release)){await this.releaseWithoutSend(client,row,'worker_disabled_before_send');await client.query('COMMIT');return {action:'disabled'};}
      if(row.launch_kind==='reminder'&&(row.can_respond!==true||row.response!==null)){await this.cancel(client,row,row.response!==null?'response_completed':'respondent_ineligible');await client.query('COMMIT');return {action:'cancelled'};}
      const unresolved=await client.query(`SELECT MIN(provider_started_at) FILTER (WHERE outcome='uncertain') AS first_uncertain_provider_started_at,COUNT(provider_started_at)::int AS provider_attempt_count FROM survey_email_attempts WHERE delivery_id=$1`,[row.id]);
      const unresolvedBoundary=unresolved.rows[0]?.first_uncertain_provider_started_at;
      if(unresolvedBoundary&&!canRetryAmbiguous({firstProviderStartedAt:unresolvedBoundary,providerAttemptCount:unresolved.rows[0]?.provider_attempt_count,createdAt:row.created_at,now:this.clock(),idempotencyHours:this.idempotencyHours,maxAttempts:this.maxAttempts,maxAgeHours:this.maxAgeHours})){await this.finalizeTerminal(client,row,'uncertain','ambiguous_retry_window_exhausted','Provider acceptance could not be reconciled safely before retry');await client.query('COMMIT');return {action:'uncertain'};}
      if(row.launch_kind==='reminder'&&!this.providerAccountScope){await this.releaseWithoutSend(client,row,'provider_scope_missing');await client.query('COMMIT');return {action:'disabled'};}
      addressBoundaryKey=`email-suppression-boundary:${this.providerAccountScope||this.environment}:${String(row.to_address).trim().toLowerCase()}`;
      await client.query(`SELECT pg_advisory_lock(hashtextextended($1,0))`,[addressBoundaryKey]);addressBoundaryLock=true;
      const suppressionControl=(await client.query(`SELECT enforcement_enabled,minimum_release FROM email_suppression_control WHERE environment=$1`,[this.environment])).rows[0];
      if(suppressionControl?.enforcement_enabled&&suppressionControl.minimum_release&&suppressionControl.minimum_release!==this.release){await this.releaseWithoutSend(client,row,'suppression_release_incompatible');await client.query('COMMIT');return {action:'disabled'};}
      if(suppressionControl?.enforcement_enabled||row.launch_kind==='reminder'){
        const blocked=await client.query(`SELECT 1 FROM email_suppressions WHERE provider_account_scope=$1 AND normalized_address=$2 AND (provider_active OR locally_overridden_at IS NULL) LIMIT 1`,[this.providerAccountScope||this.environment,String(row.to_address).trim().toLowerCase()]);
        if(blocked.rowCount){await this.cancelSuppressed(client,row);await client.query('COMMIT');return {action:'suppressed'};}
      }
      let payload;
      try{payload=buildDeliveryPayload(row,survey.name,this.environment);}
      catch{await this.finalizeTerminal(client,row,'uncertain','renderer_reconstruction_failed','Stored invitation renderer inputs could not be reconstructed safely');await client.query('COMMIT');return {action:'mismatch'};}
      if(payloadHash(payload)!==row.expected_payload_hash){await this.finalizeTerminal(client,row,'uncertain','payload_hash_mismatch','Rendered provider payload no longer matches launch snapshot');await client.query('COMMIT');return {action:'mismatch'};}
      const remaining=new Date(row.lease_expires_at).getTime()-this.clock().getTime()-2000;
      if(remaining<=1000){await this.releaseWithoutSend(client,row,'lease_too_short_before_provider');await client.query('COMMIT');return {action:'short_lease'};}
      const rateReservation=await reserveProviderRateWithAvailabilityInTransaction(client,this.rateBudgetEnvironment,this.rate);
      if(!rateReservation.reserved){await this.releaseWithoutSend(client,row,'provider_rate_wait',this.rateWaitNextAttemptAt(rateReservation));await client.query('COMMIT');return {action:'rate_wait',retryAfterMs:rateReservation.retryAfterMs};}
      await client.query(`UPDATE survey_email_attempts SET provider_started_at=now() WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[row.id,row.lease_token]);
      await client.query('COMMIT');
      let providerResult;
      try{providerResult={result:await this.provider.send(payload,{idempotencyKey:delivery.provider_idempotency_key,timeoutMs:Math.min(Number(this.env.EMAIL_PROVIDER_TIMEOUT_MS||15000),remaining)})};}
      catch(error){providerResult={error};}
      return {action:'send',row,providerResult};
    }catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{
      await unlockAdvisoryLocksAndRelease(client,[addressBoundaryLock?addressBoundaryKey:null,surveyBoundaryLock?`survey-provider-boundary:${delivery.survey_id}`:null,globalBoundaryLock?`email-provider-boundary:${this.environment}`:null]);
    }}
  async releaseWithoutSend(client,row,reason,nextAttemptAt=null){await client.query(`UPDATE survey_email_attempts SET outcome='cancelled',finished_at=now(),error_message=$3 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[row.id,row.lease_token,reason]);await client.query(`UPDATE survey_email_deliveries d SET status=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN CASE WHEN d.status='reminder_leased' THEN 'reminder_retry_wait' ELSE 'retry_wait' END WHEN d.status='reminder_leased' THEN 'reminder_pending' ELSE 'pending' END,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=CASE WHEN $3='provider_rate_wait' THEN GREATEST(LEAST(COALESCE($4::timestamptz,statement_timestamp()+interval '1 second'),statement_timestamp()+interval '1100 milliseconds'),statement_timestamp()) ELSE now() END,updated_at=now(),last_error_code=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN d.last_error_code ELSE $3 END WHERE d.id=$1 AND d.status IN ('leased','reminder_leased') AND d.lease_token=$2`,[row.id,row.lease_token,reason,nextAttemptAt]);}
  async cancel(client,row,reason){await client.query(`UPDATE survey_email_attempts SET outcome='cancelled',finished_at=now(),error_message=$3 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[row.id,row.lease_token,reason]);await client.query(`UPDATE survey_email_deliveries d SET status=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN 'uncertain' ELSE 'cancelled' END,dispatch_failed_at=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN COALESCE(d.dispatch_failed_at,now()) ELSE d.dispatch_failed_at END,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=now(),last_error_code=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN d.last_error_code ELSE $3 END WHERE d.id=$1 AND d.status IN ('leased','reminder_leased') AND d.lease_token=$2`,[row.id,row.lease_token,reason]);}
  async cancelSuppressed(client,row){await client.query(`UPDATE survey_email_attempts SET outcome='cancelled',finished_at=now(),error_message='suppressed' WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[row.id,row.lease_token]);await client.query(`UPDATE survey_email_deliveries d SET status=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN 'uncertain' ELSE 'cancelled' END,dispatch_failed_at=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN COALESCE(d.dispatch_failed_at,now()) ELSE d.dispatch_failed_at END,provider_suppressed_at=COALESCE(d.provider_suppressed_at,now()),lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=now(),last_error_code=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN d.last_error_code ELSE 'suppressed' END,last_error_message=CASE WHEN EXISTS(SELECT 1 FROM survey_email_attempts a WHERE a.delivery_id=d.id AND a.outcome='uncertain' AND a.provider_started_at IS NOT NULL) THEN d.last_error_message ELSE 'Recipient is suppressed' END WHERE d.id=$1 AND d.status IN ('leased','reminder_leased') AND d.lease_token=$2`,[row.id,row.lease_token]);}
  async finalizeTerminal(client,row,status,code,message,providerId=null){const outcome=status==='failed'?'permanent_failure':status;await client.query(`UPDATE survey_email_attempts SET outcome=$3,finished_at=now(),provider_code=$4,error_message=$5,provider_message_id=$6 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[row.id,row.lease_token,outcome,code,bounded(message),providerId]);return client.query(`UPDATE survey_email_deliveries SET status=$3,provider_message_id=COALESCE($6,provider_message_id),dispatch_accepted_at=CASE WHEN $3='accepted' THEN now() ELSE dispatch_accepted_at END,dispatch_failed_at=CASE WHEN $3 IN ('failed','uncertain') THEN now() ELSE dispatch_failed_at END,last_error_code=$4,last_error_message=$5,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND status IN ('leased','reminder_leased') AND lease_token=$2`,[row.id,row.lease_token,status,code,bounded(message),providerId]);}
  rateWaitNextAttemptAt({retryAfterMs,nextAvailableAt}){const nextTime=new Date(nextAvailableAt).getTime();return typeof retryAfterMs==='number'&&Number.isFinite(retryAfterMs)&&retryAfterMs>=0&&retryAfterMs<=1100&&Number.isFinite(nextTime)?nextAvailableAt:null;}
  rateWaitDelay(retryAfterMs){const value=typeof retryAfterMs==='number'?retryAfterMs:NaN;const jitter=Math.floor(this.random()*21);return Number.isFinite(value)&&value>=0&&value<=1100?Math.ceil(value)+5+jitter:1000+jitter;}
  backoff(attempt,retryAfter){const seconds=Number.parseInt(retryAfter,10);if(Number.isFinite(seconds)&&seconds>0)return Math.min(seconds*1000,3600000);const cap=Math.min(3600000,1000*(2**Math.min(attempt,12)));return Math.floor(this.random()*cap);}
  async finalizeFailure(row,error){const classification=classifyProviderError(error);const client=await this.pool.connect();try{await client.query('BEGIN');if(classification==='ambiguous')await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`survey-provider-boundary:${row.survey_id}`]);if(classification==='quota'){await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`email-provider-boundary:${this.environment}`]);await client.query(`UPDATE email_worker_control SET claiming_enabled=false,updated_at=now(),reason='provider quota requires operator action' WHERE environment=$1`,[this.environment]);}const locked=await client.query(`SELECT * FROM survey_email_deliveries WHERE id=$1 AND status IN ('leased','reminder_leased') AND lease_token=$2 FOR UPDATE`,[row.id,row.lease_token]);const current=locked.rows[0];if(!current){await client.query('COMMIT');return;}const providerStats=(await client.query(`SELECT COUNT(provider_started_at)::int AS provider_attempt_count,MIN(provider_started_at) FILTER (WHERE outcome='uncertain' OR (lease_token=$2 AND outcome='in_progress')) AS first_ambiguous_provider_started_at FROM survey_email_attempts WHERE delivery_id=$1`,[current.id,current.lease_token])).rows[0];if(classification==='ambiguous'){
        if(current.cancellation_requested_at)await this.finalizeTerminal(client,current,'uncertain',error.code||'ambiguous_provider_result',error.message);
        else{
          const retryAllowed=canRetryAmbiguous({firstProviderStartedAt:providerStats.first_ambiguous_provider_started_at,providerAttemptCount:providerStats.provider_attempt_count,createdAt:current.created_at,now:this.clock(),idempotencyHours:this.idempotencyHours,maxAttempts:this.maxAttempts,maxAgeHours:this.maxAgeHours});
          if(retryAllowed){const delay=this.backoff(Number(providerStats.provider_attempt_count),error.retryAfter);await client.query(`UPDATE survey_email_attempts SET outcome='uncertain',finished_at=now(),provider_code=$3,error_message=$4 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[current.id,current.lease_token,error.code,bounded(error.message)]);await client.query(`UPDATE survey_email_deliveries SET status=CASE WHEN status='reminder_leased' THEN 'reminder_retry_wait' ELSE 'retry_wait' END,next_attempt_at=now()+($3::text||' milliseconds')::interval,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,last_error_code=$4,last_error_message=$5,updated_at=now() WHERE id=$1 AND status IN ('leased','reminder_leased') AND lease_token=$2`,[current.id,current.lease_token,delay,error.code,bounded(error.message)]);}
          else await this.finalizeTerminal(client,current,'uncertain',error.code||'ambiguous_provider_result',error.message);
        }
      }
      else if(current.cancellation_requested_at)await this.cancel(client,current,'cancelled_after_provider_failure');
      else if(classification==='quota'){await client.query(`UPDATE survey_email_attempts SET outcome='transient_failure',finished_at=now(),provider_code=$3,error_message=$4 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[current.id,current.lease_token,error.code,bounded(error.message)]);await client.query(`UPDATE survey_email_deliveries SET status=CASE WHEN status='reminder_leased' THEN 'reminder_retry_wait' ELSE 'retry_wait' END,next_attempt_at=now()+interval '1 hour',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,last_error_code=$3,last_error_message=$4,updated_at=now() WHERE id=$1 AND status IN ('leased','reminder_leased') AND lease_token=$2`,[current.id,current.lease_token,error.code,bounded(error.message)]);}
      else if(classification==='transient'&&Number(providerStats.provider_attempt_count)<this.maxAttempts&&new Date(current.created_at).getTime()>this.clock().getTime()-this.maxAgeHours*3600000){const delay=this.backoff(Number(providerStats.provider_attempt_count),error.retryAfter);await client.query(`UPDATE survey_email_attempts SET outcome='transient_failure',finished_at=now(),provider_code=$3,error_message=$4 WHERE delivery_id=$1 AND lease_token=$2 AND outcome='in_progress'`,[current.id,current.lease_token,error.code,bounded(error.message)]);await client.query(`UPDATE survey_email_deliveries SET status=CASE WHEN status='reminder_leased' THEN 'reminder_retry_wait' ELSE 'retry_wait' END,next_attempt_at=now()+($3::text||' milliseconds')::interval,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,last_error_code=$4,last_error_message=$5,updated_at=now() WHERE id=$1 AND status IN ('leased','reminder_leased') AND lease_token=$2`,[current.id,current.lease_token,delay,error.code,bounded(error.message)]);}
      else await this.finalizeTerminal(client,current,'failed',error.code||'provider_error',error.message);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK').catch(()=>{});throw e;}finally{client.release();}}
  async finalizeAccepted(row,providerId){const client=await this.pool.connect();try{await client.query('BEGIN');const result=await this.finalizeTerminal(client,row,'accepted',null,null,providerId);if(result.rowCount&&row.launch_kind!=='reminder')await client.query(`UPDATE respondent SET email_sent=true WHERE respondent_id=$1 AND survey_id=$2`,[row.respondent_id,row.survey_id]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}
  async processOne(){const delivery=await this.claim();if(!delivery)return false;const started=await this.startProviderRequest(delivery);if(started.action!=='send'){if(started.action==='rate_wait')await this.sleep(this.rateWaitDelay(started.retryAfterMs));return true;}const outcome=await started.providerResult;if(outcome.error)await this.finalizeFailure(started.row,outcome.error);else await this.finalizeAccepted(started.row,outcome.result.id);return true;}
  async run(){const heartbeatMs=Math.max(3000,Number(this.env.EMAIL_HEARTBEAT_MS||10000));const timer=setInterval(()=>this.heartbeat().catch((e)=>{this.lastError=e.message;}),heartbeatMs);try{while(!this.stopped){this.claiming=await this.control();await this.heartbeat();if(!this.claiming){await this.sleep(1000);continue;}const didWork=await this.processOne();if(!didWork)await this.sleep(Number(this.env.EMAIL_IDLE_MS||750));}}finally{clearInterval(timer);this.claiming=false;await this.heartbeat().catch(()=>{});}}
  stop(){this.stopped=true;}
}

async function main(){require('./email').validateProdSecondaryResendConfig(process.env);const pool=createPool();const apiKey=process.env.RESEND_API_KEY||process.env.RESEND_KEY;const provider=apiKey?new ResendProvider({apiKey,timeoutMs:Number(process.env.EMAIL_PROVIDER_TIMEOUT_MS||15000)}):{send:async()=>{throw new Error('Email provider is disabled because no Resend API key is configured');}};const worker=new DeliveryWorker({pool,provider});const stop=()=>worker.stop();process.on('SIGTERM',stop);process.on('SIGINT',stop);try{await worker.run();}finally{await pool.end();}}
if(require.main===module)main().catch((error)=>{console.error('Email worker failed:',bounded(error.message));process.exit(1);});
module.exports={DeliveryWorker,createPool,isOutsideProviderIdempotencyWindow,canRetryAmbiguous,buildDeliveryPayload};
